import { initializeLoginController } from "./controller/LoginController";
import { initializeLogoutController } from "./controller/LogoutController";
import { toolsPanelView } from "./view/ToolsPanelView";
import { taskBarView } from "./view/TaskBarView";
import { windowMovingHandler } from "./helper/WindowMovingLogic";
import { windowResizeHandler } from "./helper/WindowResizeLogic";
import { initializeDataUpdateController } from "./controller/DataUpdateController";

initializeLoginController();
initializeLogoutController();
taskBarView.initializeViewportSizeListener();
windowMovingHandler.initializeWindowsMoveHandler();
windowResizeHandler.initializeWindowsResizeHandler();
toolsPanelView.setHidePanelHandler();
toolsPanelView.loadStocksOptions();
toolsPanelView.loadCryptoOptions();
toolsPanelView.loadStocksUpdateOptions();
toolsPanelView.loadCryptoUpdateOptions();
toolsPanelView.initializeStocksGenButtonListener();
toolsPanelView.initializeCryptoGenButtonListener();
initializeDataUpdateController();
